# Generated by Django 5.2.15 on 2026-06-05 18:31

import apps.pilgrims.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('hajj_permit_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.pilgrims.models.pilgrim_document_upload_path)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_json', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pilgrims.pilgrim')),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases_text', models.TextField(blank=True)),
                ('medications_text', models.TextField(blank=True)),
                ('allergies_text', models.TextField(blank=True)),
                ('vaccinations_text', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilgrim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='pilgrims.pilgrim')),
            ],
        ),
    ]
