# Generated by Django 5.2.15 on 2026-06-08 15:40

import apps.pilgrims.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to=apps.pilgrims.models.pilgrim_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.pilgrims.models.validate_file_size]),
        ),
    ]
