# Generated by Django 5.2.15 on 2026-06-08 20:24

import apps.pilgrims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0002_alter_medicaldocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='patient_id',
            field=models.CharField(db_index=True, default=apps.pilgrims.models.generate_patient_id, editable=False, max_length=20, unique=True),
        ),
    ]
