# Generated by Django 5.2.15 on 2026-06-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0003_pilgrim_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
