# Generated by Django 5.2.15 on 2026-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0004_pilgrim_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='triage_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
