# Generated by Django 5.2.15 on 2026-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0005_healthprofile_triage_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='cvd_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='diastolic_bp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hdl_cholesterol',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='needs_walking_assist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='systolic_bp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='total_cholesterol',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='triage_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='triage_reasoning',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='uses_oxygen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
